apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: iloop
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - data.dd-decaf.eu
    secretName: decaf-tls
  rules:
  - host: data.dd-decaf.eu
    http:
      paths:
      - path: /
        backend:
          serviceName: iloop-production
          servicePort: 80
